### ISSUE TITLE
Code from demo is not working

### ISSUE THREAD

**Issue by RomeuG** [jibon57/nativescript-braintree#10]
Hello there, I did copy the code you had from your demo, the view-model.

I created a button that, when clicked, runs your function `brainTreePayment` and when I click on it, this exception occurs:

```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onClick failed
System.err: 
System.err: TypeError: DropInRequest is not a constructor
System.err: File: "file:///data/data/org.nativescript.myappname/files/app/tns_modules/nativescript-braintree/braintree.js, line: 22, column: 28
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'Braintree.startPayment', file:'file:///data/data/org.nativescript.myappname/files/app/tns_modules/nativescript-braintree/braintree.js', line: 22, column: 29
System.err: 	Frame: function:'HelloWorldModel.brainTreePayment', file:'file:///data/data/org.nativescript.myappname/files/app/main-view-model.js', line: 26, column: 19
System.err: 	Frame: function:'HelloWorldModel.onTapPayment', file:'file:///data/data/org.nativescript.myappname/files/app/main-view-model.js', line: 65, column: 14
System.err: 	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.myappname/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 107, column: 32
System.err: 	Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.myappname/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
System.err: 	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.myappname/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:17)
System.err: 	at android.view.View.performClick(View.java:6294)
System.err: 	at android.view.View$PerformClick.run(View.java:24774)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6501)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by jibon57** [comment]
`tns platform remove android
tns prepare android
tns run android`
